### ISSUE TITLE
test outcome statP diverges among different python environments

### ISSUE THREAD

**Issue by sheyma** [MICA-MNI/BrainStat#53] opened 2020-11-24 16:31 UTC
Currently all tests in **/BrainStat/surfstat/tests** are running successfully, except for one: **test_20** in **tests/test_SurfStatP.py**.

In fact, this test is running successfully in @ReinderVosDeWael conda environment, whereas it fails in @sheyma's. 

Reproducing the relevant testing is below.

`$ python3 -m pytest -s tests/test_SurfStatP.py  -k test_20`

Expected behaviour is to have no assertion error, meaning that all outputs of SurfStatP.py and SurfStatP.m should be the same. 

I can provide my conda environment, if anybody wants to reproduce the problem.

**Comment by ReinderVosDeWael** [comment] 2020-11-24 16:32
Can you send your conda's .yml?

**Comment by sheyma** [comment] 2020-11-24 17:01
Let me see if it works out with attaching a text file
[sheymaenv.txt](https://github.com/MICA-MNI/BrainStat/files/5591490/sheymaenv.txt)

**Comment by sheyma** [comment] 2020-11-24 17:01
yeap, it should have worked now.

**Comment by ReinderVosDeWael** [comment] 2020-11-24 17:07
which python version is this

**Comment by sheyma** [comment] 2020-11-24 17:10
`Python 3.6.10`
`conda 4.8.3`

**Comment by ReinderVosDeWael** [comment] 2020-11-24 17:20
Can you export this as a YAML file? I can’t get it to parse the .txt file.
```
conda env export --name ENVNAME > envname.yml
```
-----------------------------------------------------
Reinder Vos de Wael
Doctoral Candidate, McGill University

+1 (514) 246 5799 | reinder.vosdewael@gmail.com
Room WB214B, Montreal Neurological Institute, Montreal, QC H3A 2B4, Canada

**Comment by sheyma** [comment] 2020-11-24 20:00
not possible to attach *yml here.
here is the dummy way:

```
name: surfstat
channels:
  - r
  - conda-forge/label/cf201901
  - pspuhler
  - anaconda
  - aramislab
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - absl-py=0.10.0=py36h9f0ad1d_1
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=hc3fd857_29
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36he6145b8_1001
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.11.8=ha878542_0
  - cairo=1.16.0=h488836b_1006
  - certifi=2020.11.8=py36h5fab9bb_0
  - cffi=1.14.3=py36h829019c_1
  - chardet=3.0.4=py36h9880bd3_1008
  - ci-info=0.2.0=pyh9f0ad1d_0
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.1.1=py36h5d711a5_1
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h7a60e0d_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - duecredit=0.6.4=py36_0
  - entrypoints=0.3=py36h9f0ad1d_1002
  - etelemetry=0.2.2=pyh9f0ad1d_0
  - expat=2.2.9=he1b5a44_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - flake8=3.8.4=py_0
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.4=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=he2a3fca_29
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=7.5.0=hfca37b7_17
  - gfortran_linux-64=7.5.0=ha081f1e_29
  - glib=2.66.1=he1b5a44_1
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=he1b5a44_1001
  - grpcio=1.33.2=py36he0f7d3b_2
  - gsl=2.6=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h547f3ba_29
  - h5py=2.10.0=nompi_py36h513d04c_102
  - harfbuzz=2.7.2=hb1ce69c_1
  - hdf5=1.10.5=nompi_h54c07f9_1110
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.0=py36h95af2a2_0
  - ipython=7.16.1=py36h95af2a2_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - isodate=0.6.0=py_1
  - jedi=0.17.2=py36h9f0ad1d_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - keepalive=0.5=py36h9f0ad1d_4
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py36hdb11119_1
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglib=2.66.1=h0dae87d_1
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_5
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_2
  - libprotobuf=3.13.0.1=h8b12597_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=h572872d_1
  - lxml=4.6.1=py36h17c4326_0
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=hd18ef5c_1
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py36he6145b8_2
  - matlab_engine=R2017a=py_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h8c4c3a4_1002
  - more-itertools=8.5.0=py_0
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - nb_conda=2.2.1=py36_2
  - nb_conda_kernels=2.3.0=py36h9f0ad1d_3
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36h9f0ad1d_1
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he1b5a44_2
  - nest-asyncio=1.4.1=py_0
  - networkx=2.5=py_0
  - neurdflib=5.0.1=py_0
  - nipype=1.5.0=py36h9f0ad1d_0
  - notebook=6.0.3=py36h9f0ad1d_1
  - nspr=4.29=he1b5a44_1
  - nss=3.58=h27285de_1
  - numpy=1.19.2=py36h68c22af_1
  - numpy_groupies=0.9.8.4=py_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.11.0.2=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h80147aa_5
  - parso=0.7.1=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.0.2=py36_1
  - pixman=0.38.0=h516909a_1003
  - plotly=4.8.1=pyh9f0ad1d_0
  - pluggy=0.13.1=py36h9f0ad1d_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - protobuf=3.13.0.1=py36h201607c_1
  - prov=1.5.3=py_0
  - psutil=5.7.2=py36he6145b8_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydicom=2.0.0=pyh9f0ad1d_0
  - pydotplus=2.0.2=py_1
  - pyflakes=2.2.0=py_0
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py36haa643ae_4
  - pyrsistent=0.17.3=py36h8c4c3a4_1
  - pysocks=1.7.1=py36h9880bd3_2
  - pytest=5.4.3=py36h9f0ad1d_0
  - python=3.6.10=h8356626_1010_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pyzmq=19.0.2=py36h9947dbf_2
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - r-base=3.6.3=hd272fe0_4
  - r-freesurferformats=0.1.0=r36h6115d3f_0
  - rdflib=5.0.0=py36h9f0ad1d_3
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - retrying=1.3.3=py_2
  - scipy=1.5.2=py36h3a855aa_2
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - sed=4.8=hbfbb72e_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py36h9880bd3_2
  - simplejson=3.17.2=py36h8c4c3a4_1
  - six=1.15.0=pyh9f0ad1d_0
  - sparqlwrapper=1.8.5=py36h9f0ad1d_1004
  - sqlite=3.33.0=h4cf870e_1
  - statsmodels=0.12.0=py36h68bb277_1
  - sysroot_linux-64=2.12=h77966d4_13
  - tensorboard=1.14.0=py36_0
  - tensorflow=1.14.0=hc3e5e64_0
  - tensorflow-base=1.14.0=py36hc3e5e64_0
  - tensorflow-estimator=1.14.0=py36h5ca1d4c_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.1=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=h555a92e_3
  - tornado=6.0.4=py36h8c4c3a4_2
  - traitlets=4.3.3=py36h9f0ad1d_1
  - traits=6.1.0=py36h8c4c3a4_1
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_4
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xvfbwrapper=0.2.9=py36h9f0ad1d_1002
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - biopython==1.78
    - brainspace==0.1.1
    - citeproc-py==0.4.0
    - future==0.18.2
    - fuzzywuzzy==0.18.0
    - joblib==0.15.1
    - jupyter==1.0.0
    - mpmath==1.1.0
    - neurosynth==0.3.8
    - nibabel==3.1.0
    - nilearn==0.7.0
    - nimare==0.0.3+213.g8dc6c55
    - pandas==1.0.5
    - pillow==7.1.2
    - ply==3.11
    - pymare==0.0.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytz==2020.1
    - scikit-learn==0.23.1
    - sympy==1.7rc1
    - threadpoolctl==2.1.0
    - tqdm==4.53.0
    - vtk==9.0.1
    - wrapt==1.12.1
prefix: /data/u_bayrak_software/anaconda2/envs/surfstat
```

**Comment by ReinderVosDeWael** [comment] 2021-04-09 17:29
@sheyma Have you ever been able to reproduce this issue? If not shall we close this - I've never heard of or encountered this issue since this was posted.

**Closed** 2021-05-03 07:49 UTC
